services:
  Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
    public: true
    abstract: true

  Controller\DefaultController:
    arguments:
      - '@Domain\Tmdb\Model\TmdbModel'
    parent: Symfony\Bundle\FrameworkBundle\Controller\AbstractController
