services:
  TmdbApi\Common:
    arguments:
      - '%tmdb.url%'
      - '%tmdb.api_key%'

  Domain\Tmdb\Model\TmdbModel:
    arguments:
      - '@TmdbApi\Common'
    public: true

  app.exception_listener:
    class: Application\Listener\ExceptionListener
    arguments:
      - '%kernel.environment%'
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
