version: '3'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    environment:
      TIMEZONE: Europe/Moscow
      XDEBUG_CONFIG: remote_host=172.30.0.1 remote_enable=1
      TZ: Europe/Moscow
    volumes:
      - './docker/php/php.ini:/usr/local/etc/php/php.ini'
      - './:/var/www/app:cached'
    working_dir: /var/www/app
    entrypoint:
      - /bin/sh
    command: ["-c", "composer install && php-fpm"]
  nginx:
    image: nginx
    environment:
      TZ: Europe/Moscow
    depends_on:
      - php
    volumes:
      - './:/var/www/app:cached'
      - './docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
